#!/usr/bin/env python

from calc import add

def main():
    import sys
    if len(sys.argv) != 3:
        print("Usage: add2vals X Y")
        return
    try:
        arg1 = float(sys.argv[1])
        arg2 = float(sys.argv[2])
    except ValueError:
        print("Both arguments must be numbers")
        return

    result = add(arg1, arg2)
    print(f"The sum is {result}")

if __name__ == "__main__":
    main()

